postprocessor:
  name: neco
  APS_mode: False
  postprocessor_args:
    neco_dim: 100
    use_scaler: True
    multiply_maxlogit: False
    eps: 1e-12
  postprocessor_sweep:
    neco_dim_list: [50, 100, 150, 200]
